-- Migration: Create orders table
-- Description: Orders for concrete/bricks with advance payment and status tracking

CREATE TABLE IF NOT EXISTS `orders` (
  `id` char(36) COLLATE utf8mb4_general_ci NOT NULL,
  `order_number` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `customer_id` char(36) COLLATE utf8mb4_general_ci NOT NULL,
  `created_by` char(36) COLLATE utf8mb4_general_ci NOT NULL,
  `product_type` enum('concrete','bricks','other') COLLATE utf8mb4_general_ci NOT NULL,
  `product_description` text COLLATE utf8mb4_general_ci,
  `quantity` decimal(10,2) NOT NULL DEFAULT 0,
  `unit` varchar(20) COLLATE utf8mb4_general_ci DEFAULT 'units',
  `unit_price` decimal(12,2) DEFAULT NULL,
  `total_amount` decimal(12,2) DEFAULT NULL,
  `advance_amount` decimal(12,2) DEFAULT NULL,
  `delivery_address` text COLLATE utf8mb4_general_ci,
  `notes` text COLLATE utf8mb4_general_ci,
  `status` enum('placed','assigned','dispatched','delivered','invoiced','cancelled') COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'placed',
  `advance_paid` tinyint DEFAULT 0,
  `advance_paid_at` timestamp NULL DEFAULT NULL,
  `advance_payment_method` enum('cash','bank') COLLATE utf8mb4_general_ci DEFAULT NULL,
  `advance_upi_id` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `balance_paid` tinyint DEFAULT 0,
  `balance_paid_at` timestamp NULL DEFAULT NULL,
  `balance_payment_method` enum('cash','bank') COLLATE utf8mb4_general_ci DEFAULT NULL,
  `balance_upi_id` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `assigned_to` char(36) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `dispatched_at` timestamp NULL DEFAULT NULL,
  `delivered_at` timestamp NULL DEFAULT NULL,
  `invoiced_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number` (`order_number`),
  KEY `idx_orders_customer` (`customer_id`),
  KEY `idx_orders_status` (`status`),
  KEY `idx_orders_created_by` (`created_by`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
