import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  StatusBar,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { getLogoBase64, getPdfTimestamp, getPdfHeaderFooterCSS, getPdfLogoHtml, getPdfTimestampHtml } from '../../../utils/pdfUtils';
import { useAuth } from '../../../hooks/useAuth';
import { useScrollPosition } from '../../../hooks/useScrollPosition';
import { quotationsApi } from '../api';
import { reportsApi } from '../../reports/api';
import { auditApi } from '../../audit/api';
import { paymentsApi } from '../../payments/api';
import { useTheme } from '../../../context/ThemeContext';
import AppHeader from '../../../components/common/AppHeader';
import BottomNavigation from '../../../components/common/BottomNavigation';

const ViewQuotationScreen = ({ route, navigation }) => {
  const { projectId } = route.params;
  const { user } = useAuth();
  const { colors } = useTheme();
  const styles = React.useMemo(() => getStyles(colors), [colors]);
  const { scrollY, onScroll } = useScrollPosition();
  const { colors: themeColors } = useTheme();
  
  const [loading, setLoading] = useState(true);
  const [approving, setApproving] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState(null);
  
  // Quotation data
  const [quotationId, setQuotationId] = useState(null);
  const [materialCost, setMaterialCost] = useState(0);
  const [labourCost, setLabourCost] = useState(0);
  const [transportCost, setTransportCost] = useState(0);
  const [otherCost, setOtherCost] = useState(0);
  const [totalCost, setTotalCost] = useState(0);
  const [advanceAmount, setAdvanceAmount] = useState(0);
  const [isApproved, setIsApproved] = useState(false);
  const [approvedAt, setApprovedAt] = useState(null);
  const [createdAt, setCreatedAt] = useState(null);
  const [generatedBy, setGeneratedBy] = useState('');
  
  // Project data
  const [projectName, setProjectName] = useState('');
  const [projectLocation, setProjectLocation] = useState('');
  const [projectStatus, setProjectStatus] = useState('');
  
  // Payment data
  const [extraCharges, setExtraCharges] = useState([]);
  const [pendingExtraCharges, setPendingExtraCharges] = useState([]);
  const [loadingExtraCharges, setLoadingExtraCharges] = useState(false);
  const [paymentSummary, setPaymentSummary] = useState(null);
  const [loadingPaymentSummary, setLoadingPaymentSummary] = useState(false);
  
  // Advance payment status
  const [isAdvancePaid, setIsAdvancePaid] = useState(false);
  const [advancePayment, setAdvancePayment] = useState(null);

  useEffect(() => {
    loadData();
  }, [projectId]);

  const loadData = async () => {
    try {
      setLoading(true);
      setError(null);
      
      // Fetch quotation first
      const response = await quotationsApi.getQuotationsByProject(projectId);
      
      if (!response.success || !response.data.quotations || response.data.quotations.length === 0) {
        setError('No quotation found for this project');
        setLoading(false);
        return;
      }

      const quotation = response.data.quotations[0];
      
      setQuotationId(quotation.id);
      setMaterialCost(quotation.material_cost || 0);
      setLabourCost(quotation.labour_cost || 0);
      setTransportCost(quotation.transport_cost || 0);
      setOtherCost(quotation.other_cost || 0);
      setTotalCost(quotation.total_cost || 0);
      setAdvanceAmount(quotation.advance_amount || 0);
      setIsApproved(quotation.approved || false);
      setApprovedAt(quotation.approved_at);
      setCreatedAt(quotation.created_at);
      
      // Get detailed quotation with report
      const detailResponse = await quotationsApi.getQuotationById(quotation.id);
      
      console.log('Detail Response:', JSON.stringify(detailResponse, null, 2));
      
      if (detailResponse.success && detailResponse.data) {
        console.log('Generated by name:', detailResponse.data.generated_by_name);
        
        // Get project name from quotation data
        if (detailResponse.data.project_name) {
          setProjectName(detailResponse.data.project_name);
        }
        if (detailResponse.data.project_location) {
          setProjectLocation(detailResponse.data.project_location);
        }
        if (detailResponse.data.project_status) {
          setProjectStatus(detailResponse.data.project_status);
        }
        // Get generated by name
        if (detailResponse.data.generated_by_name) {
          setGeneratedBy(detailResponse.data.generated_by_name);
        } else {
          console.log('No generated_by_name found, using fallback');
          setGeneratedBy('N/A');
        }
      }
      
      // Try to fetch project details as fallback
      if (!projectName) {
        try {
          const { projectsApi } = await import('../../projects/api');
          const projectResponse = await projectsApi.getProjectById(projectId);
          if (projectResponse.success && projectResponse.data && projectResponse.data.project) {
            setProjectName(projectResponse.data.project.name || `Project ${projectId}`);
            setProjectLocation(projectResponse.data.project.location || '');
            setProjectStatus(projectResponse.data.project.status || '');
          }
        } catch (err) {
          console.log('Could not fetch project details:', err);
          setProjectName(`Project ${projectId}`);
        }
      }
      
      setLoading(false);
      
      // Fetch payment data after quotation is loaded
      await fetchPaymentData();
      
    } catch (err) {
      console.error('Error loading data:', err);
      setError(err.message || 'Failed to load quotation');
      setLoading(false);
    }
  };

  const fetchPaymentData = async () => {
    try {
      setLoadingExtraCharges(true);
      setLoadingPaymentSummary(true);
      
      const paymentsResponse = await paymentsApi.getPaymentsByProject(projectId);
      const payments = paymentsResponse.data.payments || [];
      
      // Filter extra charges
      const extraPayments = payments.filter(p => p.type === 'extra');
      setExtraCharges(extraPayments);
      
      // Filter pending extra charges (only show if payment_method exists and status is pending)
      const pendingExtra = extraPayments.filter(p => 
        p.status === 'pending' && p.payment_method !== null
      );
      setPendingExtraCharges(pendingExtra);
      
      // Check for advance payment
      const advancePayments = payments.filter(p => 
        p.type === 'advance' || (p.type === 'regular' && p.description?.toLowerCase().includes('advance'))
      );
      
      const paidAdvance = advancePayments.find(p => p.status === 'completed');
      if (paidAdvance) {
        setIsAdvancePaid(true);
        setAdvancePayment(paidAdvance);
      } else {
        setIsAdvancePaid(false);
        setAdvancePayment(null);
      }
      
      // Build payment summary
      const quotationResponse = await quotationsApi.getQuotationsByProject(projectId);
      const quotation = quotationResponse?.data?.quotations?.[0];
      
      if (quotation) {
        const regularPayments = payments.filter(p => p.type !== 'extra');
        const extraChargesList = payments.filter(p => p.type === 'extra');
        
        const totalPaid = payments
          .filter(p => p.status === 'completed')
          .reduce((sum, p) => sum + parseFloat(p.amount || 0), 0);
        
        const extraChargesTotal = extraChargesList
          .reduce((sum, p) => sum + parseFloat(p.amount || 0), 0);
        
        const totalCostWithExtras = parseFloat(quotation.total_cost || 0) + extraChargesTotal;
        const balance = totalCostWithExtras - totalPaid;
        
        const hasPendingFinalPayment = payments.some(
          p => p.type === 'final' && p.status === 'pending'
        );
        
        setPaymentSummary({
          totalCost: parseFloat(quotation.total_cost || 0),
          extraChargesTotal,
          totalCostWithExtras,
          totalPaid,
          balance,
          payments,
          extraCharges: extraChargesList,
          pendingExtraCharges: pendingExtra,
          hasPendingFinalPayment,
        });
      }
      
    } catch (err) {
      console.error('Error fetching payment data:', err);
    } finally {
      setLoadingExtraCharges(false);
      setLoadingPaymentSummary(false);
    }
  };

  const handleApprove = () => {
    Alert.alert(
      'Approve Quotation',
      'Are you sure you want to approve this quotation?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Approve',
          onPress: async () => {
            try {
              setApproving(true);
              await quotationsApi.approveQuotation(quotationId);
              setIsApproved(true);
              setApprovedAt(new Date().toISOString());
              Alert.alert('Success', 'Quotation approved successfully.', [
                { text: 'OK', onPress: () => {
                  navigation.navigate('CustomerHomeMain', { refresh: true });
                }}
              ]);
            } catch (err) {
              Alert.alert('Error', err.message || 'Failed to approve quotation');
              setApproving(false);
            }
          },
        },
      ]
    );
  };

  const handlePayAdvance = () => {
    if (!projectId) {
      Alert.alert('Error', 'Project information is missing');
      return;
    }
    
    // Navigate to CreatePayment with project data
    navigation.navigate('CreatePayment', { 
      project: {
        id: projectId,
        name: projectName,
        location: projectLocation,
        status: projectStatus,
        customer_id: user?.id
      }
    });
  };

  const handlePayExtraCharge = (extraCharge) => {
    navigation.navigate('PayExtraCharge', { 
      project: {
        id: projectId,
        name: projectName,
        location: projectLocation,
        status: projectStatus,
        customer_id: user?.id
      }, 
      extraCharge 
    });
  };

  const handleViewReport = async () => {
    try {
      // Fetch reports for this project
      const response = await reportsApi.getReportsByProject(projectId);
      
      if (!response.success || !response.data.reports || response.data.reports.length === 0) {
        Alert.alert('No Report Found', 'No site report has been submitted for this project yet.');
        return;
      }

      // Sort reports by created_at date (newest first)
      const sortedReports = [...response.data.reports].sort((a, b) => {
        try {
          const dateA = a.created_at ? new Date(a.created_at) : new Date(0);
          const dateB = b.created_at ? new Date(b.created_at) : new Date(0);
          return dateB.getTime() - dateA.getTime();
        } catch {
          return 0;
        }
      });

      // Get the latest report
      const latestReport = sortedReports[0];
      
      // Navigate to ViewReport with both projectId and reportId
      navigation.navigate('ViewReport', { 
        projectId, 
        reportId: latestReport.id 
      });
    } catch (err) {
      console.error('Error fetching reports:', err);
      Alert.alert('Error', 'Failed to fetch site report. Please try again.');
    }
  };

  const formatCurrency = (amount) => {
    const num = parseFloat(amount) || 0;
    return `₹${num.toFixed(2)}`;
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    try {
      const date = new Date(dateString);
      return date.toLocaleDateString('en-IN', { 
        day: 'numeric', 
        month: 'short', 
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    } catch {
      return 'N/A';
    }
  };

  const getProjectStatusColor = (status) => {
    const colors = {
      'pending': '#F59E0B',
      'in_progress': '#3B82F6', 
      'completed': '#10B981',
      'on_hold': '#F59E0B',
      'cancelled': '#EF4444',
      'closed': '#6B7280',
      'quotation_generated': '#8B5CF6',
      'customer_approved': '#10B981',
      'report_submitted': '#3B82F6',
      'advance_paid': '#10B981',
      'work_started': '#3B82F6',
    };
    return colors[status?.toLowerCase()] || '#6B7280';
  };

  const getProjectStatusText = (status) => {
    const statusTexts = {
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'completed': 'Completed', 
      'on_hold': 'On Hold',
      'cancelled': 'Cancelled',
      'closed': 'Closed',
      'quotation_generated': 'Quotation Generated',
      'customer_approved': 'Customer Approved',
      'report_submitted': 'Report Submitted',
      'advance_paid': 'Advance Paid',
      'work_started': 'Work Started',
    };
    return statusTexts[status?.toLowerCase()] || status || 'Unknown';
  };

  const downloadPDF = async () => {
    try {
      setDownloading(true);

      const logoBase64 = await getLogoBase64();
      const timestamp = getPdfTimestamp();
      const displayProjectName = projectName || `Project ${projectId}`;
      
      // Generate extra charges HTML
      let extraChargesHTML = '';
      if (extraCharges && extraCharges.length > 0) {
        extraChargesHTML = `
          <div class="section">
            <div class="section-title">Extra Charges</div>
            ${extraCharges.map(charge => `
              <div class="row">
                <span class="label">${charge.description || 'Extra Charge'}</span>
                <span class="value ${charge.status === 'pending' ? 'warning' : ''}">${formatCurrency(charge.amount)}</span>
              </div>
            `).join('')}
            <div class="row total-row">
              <span>Total Extra Charges:</span>
              <span class="total-value">${formatCurrency(extraCharges.reduce((sum, c) => sum + parseFloat(c.amount || 0), 0))}</span>
            </div>
          </div>
        `;
      }

      // Generate advance payment HTML
      let advancePaymentHTML = '';
      if (isAdvancePaid && advancePayment) {
        advancePaymentHTML = `
          <div class="advance-paid-badge">
            <span>✓ Advance Paid on ${formatDate(advancePayment.paid_at || advancePayment.created_at)}</span>
          </div>
        `;
      }

      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Quotation - ${displayProjectName}</title>
          <style>
            body {
              font-family: 'Helvetica', 'Arial', sans-serif;
              padding: 30px;
              color: #1E293B;
              background: #F8FAFC;
            }
            ${getPdfHeaderFooterCSS()}
            .header {
              text-align: center;
              margin-bottom: 30px;
              padding: 20px;
              background: linear-gradient(135deg, #3B82F6, #1E3A8A);
              border-radius: 15px;
              color: white;
            }
            .header h1 {
              margin: 0;
              font-size: 32px;
              font-weight: 800;
            }
            .header p {
              margin: 5px 0 0;
              opacity: 0.9;
            }
            .status-badge {
              display: inline-block;
              padding: 8px 20px;
              border-radius: 25px;
              font-weight: bold;
              color: white;
              background: ${isApproved ? '#10B981' : '#F59E0B'};
              margin: 10px 0;
            }
            .advance-paid-badge {
              display: inline-block;
              padding: 8px 20px;
              border-radius: 25px;
              font-weight: bold;
              color: white;
              background: #10B981;
              margin: 10px 0;
            }
            .section {
              background: white;
              border-radius: 15px;
              padding: 20px;
              margin: 20px 0;
              box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            }
            .section-title {
              color: #3B82F6;
              font-size: 20px;
              font-weight: 700;
              margin-bottom: 15px;
              border-bottom: 2px solid #DBEAFE;
              padding-bottom: 10px;
            }
            .row {
              display: flex;
              justify-content: space-between;
              padding: 12px 0;
              border-bottom: 1px solid #E2E8F0;
            }
            .row:last-child {
              border-bottom: none;
            }
            .label {
              color: #64748B;
              font-weight: 600;
            }
            .value {
              color: #1E293B;
              font-weight: 500;
            }
            .warning {
              color: #F59E0B;
              font-weight: 600;
            }
            .total-row {
              display: flex;
              justify-content: space-between;
              padding: 15px 0;
              font-size: 18px;
              font-weight: bold;
              border-top: 2px solid #3B82F6;
              margin-top: 10px;
            }
            .total-value {
              color: #3B82F6;
            }
            .payment-summary {
              background: #F0F9FF;
              border-radius: 15px;
              padding: 20px;
              margin: 20px 0;
            }
            .payment-row {
              display: flex;
              justify-content: space-between;
              padding: 8px 0;
            }
            .payment-label {
              color: #64748B;
            }
            .payment-value {
              font-weight: 600;
            }
            .payment-value.success {
              color: #10B981;
            }
            .payment-value.danger {
              color: #EF4444;
            }
            .footer {
              text-align: center;
              margin-top: 30px;
              color: #94A3B8;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          ${getPdfLogoHtml(logoBase64)}
          <div class="header">
            <h1>QUOTATION</h1>
            <p>${displayProjectName}</p>
          </div>
          
          <div style="text-align: center;">
            <span class="status-badge">${isApproved ? 'APPROVED' : 'PENDING'}</span>
            ${advancePaymentHTML}
          </div>

          <div class="section">
            <div class="section-title">Project Information</div>
            <div class="row">
              <span class="label">Project ID:</span>
              <span class="value">${projectId}</span>
            </div>
            ${projectLocation ? `
            <div class="row">
              <span class="label">Location:</span>
              <span class="value">${projectLocation}</span>
            </div>
            ` : ''}
            <div class="row">
              <span class="label">Created:</span>
              <span class="value">${formatDate(createdAt)}</span>
            </div>
            ${isApproved && approvedAt ? `
            <div class="row">
              <span class="label">Approved:</span>
              <span class="value">${formatDate(approvedAt)}</span>
            </div>
            ` : ''}
          </div>

          <div class="section">
            <div class="section-title">Cost Breakdown</div>
            <div class="row">
              <span class="label">Material Cost:</span>
              <span class="value">${formatCurrency(materialCost)}</span>
            </div>
            <div class="row">
              <span class="label">Labour Cost:</span>
              <span class="value">${formatCurrency(labourCost)}</span>
            </div>
            <div class="row">
              <span class="label">Transport Cost:</span>
              <span class="value">${formatCurrency(transportCost)}</span>
            </div>
            <div class="row">
              <span class="label">Other Cost:</span>
              <span class="value">${formatCurrency(otherCost)}</span>
            </div>
            <div class="total-row">
              <span>Base Total Cost:</span>
              <span class="total-value">${formatCurrency(totalCost)}</span>
            </div>
            ${advanceAmount > 0 ? `
            <div class="row" style="margin-top: 10px; background: #FFFBEB; border-radius: 8px; padding: 12px;">
              <span class="label" style="color: #92400E;">Advance Required:</span>
              <span class="value" style="color: #F59E0B; font-weight: 700;">${formatCurrency(advanceAmount)}</span>
            </div>
            ` : ''}
          </div>

          ${extraChargesHTML}

          ${paymentSummary ? `
          <div class="payment-summary">
            <div class="section-title" style="border-bottom-color: #BFDBFE;">Payment Summary</div>
            <div class="payment-row">
              <span class="payment-label">Total Paid:</span>
              <span class="payment-value success">${formatCurrency(paymentSummary.totalPaid)}</span>
            </div>
            <div class="payment-row">
              <span class="payment-label">Balance Due:</span>
              <span class="payment-value ${paymentSummary.balance > 0 ? 'danger' : 'success'}">${formatCurrency(paymentSummary.balance)}</span>
            </div>
          </div>
          ` : ''}

          <div class="footer">
            Generated on ${new Date().toLocaleString()}
          </div>
          ${getPdfTimestampHtml(timestamp)}
        </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });

      const fileName = `quotation-${projectId}-${Date.now()}.pdf`;
      const fileUri = FileSystem.documentDirectory + fileName;
      
      await FileSystem.moveAsync({
        from: uri,
        to: fileUri,
      });

      const isAvailable = await Sharing.isAvailableAsync();
      if (isAvailable) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Save Quotation PDF',
        });
        auditApi.logShare('PDF', 'Quotation', String(projectId), projectName || String(projectId));
      } else {
        Alert.alert('Success', `PDF saved to ${fileUri}`);
      }
    } catch (error) {
      console.error('Error generating PDF:', error);
      Alert.alert('Error', 'Failed to generate PDF');
    } finally {
      setDownloading(false);
    }
  };

  const downloadCSV = async () => {
    try {
      setDownloading(true);
      const rows = [
        ['Field', 'Value'],
        ['Project', projectName || projectId],
        ['Location', projectLocation || ''],
        ['Status', isApproved ? 'Approved' : 'Pending'],
        ['Created', createdAt ? new Date(createdAt).toLocaleDateString('en-IN') : ''],
        ['Approved At', approvedAt ? new Date(approvedAt).toLocaleDateString('en-IN') : ''],
        ['Material Cost', materialCost],
        ['Labour Cost', labourCost],
        ['Transport Cost', transportCost],
        ['Other Cost', otherCost],
        ['Total Cost', totalCost],
        ['Advance Required', advanceAmount],
        ...extraCharges.map(e => [`Extra: ${e.description || 'Charge'}`, e.amount]),
        ['Total Paid', paymentSummary?.totalPaid || ''],
        ['Balance Due', paymentSummary?.balance || ''],
      ];
      const csv = rows.map(r => r.map(v => `"${String(v ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
      const uri = FileSystem.cacheDirectory + `quotation-${projectId}.csv`;
      await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 });
      await Sharing.shareAsync(uri, { mimeType: 'text/csv', UTI: 'public.comma-separated-values-text' });
      auditApi.logShare('CSV', 'Quotation', String(projectId), projectName || String(projectId));
    } catch (e) {
      Alert.alert('Error', 'Failed to export CSV');
    } finally {
      setDownloading(false);
    }
  };

  const downloadExcel = async () => {
    try {
      setDownloading(true);
      const rows = [
        ['Field', 'Value'],
        ['Project', projectName || projectId],
        ['Location', projectLocation || ''],
        ['Status', isApproved ? 'Approved' : 'Pending'],
        ['Created', createdAt ? new Date(createdAt).toLocaleDateString('en-IN') : ''],
        ['Approved At', approvedAt ? new Date(approvedAt).toLocaleDateString('en-IN') : ''],
        ['Material Cost', materialCost],
        ['Labour Cost', labourCost],
        ['Transport Cost', transportCost],
        ['Other Cost', otherCost],
        ['Total Cost', totalCost],
        ['Advance Required', advanceAmount],
        ...extraCharges.map(e => [`Extra: ${e.description || 'Charge'}`, e.amount]),
        ['Total Paid', paymentSummary?.totalPaid || ''],
        ['Balance Due', paymentSummary?.balance || ''],
      ];
      const xml = `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Quotation"><Table>${
        rows.map(r => `<Row>${r.map(v => `<Cell><Data ss:Type="String">${String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</Data></Cell>`).join('')}</Row>`).join('')
      }</Table></Worksheet></Workbook>`;
      const uri = FileSystem.cacheDirectory + `quotation-${projectId}.xls`;
      await FileSystem.writeAsStringAsync(uri, xml, { encoding: FileSystem.EncodingType.UTF8 });
      await Sharing.shareAsync(uri, { mimeType: 'application/vnd.ms-excel', UTI: 'com.microsoft.excel.xls' });
      auditApi.logShare('Excel', 'Quotation', String(projectId), projectName || String(projectId));
    } catch (e) {
      Alert.alert('Error', 'Failed to export Excel');
    } finally {
      setDownloading(false);
    }
  };

  if (loading) {
    return (
      <View style={[styles.centerContainer, { backgroundColor: themeColors.background }]}>
        <StatusBar barStyle="light-content" backgroundColor="transparent" translucent />
        <AppHeader navigation={navigation} />
        <View style={styles.loadingContent}>
          <LinearGradient
            colors={['#3B82F6', '#1E3A8A']}
            style={styles.loadingCircle}
          >
            <MaterialCommunityIcons name="file-document-outline" size={40} color="#FFF" />
          </LinearGradient>
          <Text style={styles.loadingText}>Loading quotation details...</Text>
          <ActivityIndicator size="large" color="#3B82F6" style={styles.loadingIndicator} />
        </View>
      </View>
    );
  }

  if (error) {
    return (
      <View style={[styles.centerContainer, { backgroundColor: themeColors.background }]}>
        <StatusBar barStyle="light-content" backgroundColor="transparent" translucent />
        <AppHeader navigation={navigation} />
        <View style={styles.errorContent}>
          <View style={styles.errorIconContainer}>
            <MaterialCommunityIcons name="alert-circle-outline" size={60} color="#EF4444" />
          </View>
          <Text style={styles.errorText}>{error}</Text>
          <TouchableOpacity style={styles.retryButton} onPress={loadData}>
            <LinearGradient
              colors={['#3B82F6', '#1E3A8A']}
              style={styles.retryButtonGradient}
            >
              <MaterialCommunityIcons name="refresh" size={20} color="#FFF" />
              <Text style={styles.retryButtonText}>Try Again</Text>
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  const canApprove = user?.role === 'customer' && !isApproved;
  const canPayAdvance = user?.role === 'customer' && isApproved && advanceAmount > 0 && !isAdvancePaid;
  const hasPendingExtras = pendingExtraCharges.length > 0;
  const displayProjectName = projectName || `Project ${projectId}`;

  return (
    <View style={[styles.container, { backgroundColor: themeColors.background }]}>
      <StatusBar barStyle="light-content" backgroundColor="transparent" translucent />
      <AppHeader navigation={navigation} />
      
      <ScrollView 
        style={styles.scrollView} 
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        onScroll={onScroll}
        scrollEventThrottle={16}
      >
        {/* Project Header - Enhanced */}
        <LinearGradient
          colors={['#3B82F6', '#1E3A8A']}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.projectHeader}
        >
          <View style={styles.projectHeaderContent}>
            <View style={styles.projectTitleContainer}>
              <MaterialCommunityIcons name="office-building" size={24} color="#FFF" />
              <Text style={styles.projectNameText}>{displayProjectName}</Text>
            </View>
            
            <View style={styles.statusContainer}>
              <View style={[
                styles.statusIndicator,
                { backgroundColor: isApproved ? '#10B981' : '#F59E0B' }
              ]}>
                <MaterialCommunityIcons 
                  name={isApproved ? 'check-circle' : 'clock-outline'} 
                  size={14} 
                  color="#FFF" 
                />
                <Text style={styles.statusText}>
                  {isApproved ? 'APPROVED' : 'PENDING'}
                </Text>
              </View>
            </View>
          </View>
          
          {projectLocation ? (
            <View style={styles.locationContainer}>
              <MaterialCommunityIcons name="map-marker" size={16} color="rgba(255,255,255,0.9)" />
              <Text style={styles.locationText}>{projectLocation}</Text>
            </View>
          ) : null}
        </LinearGradient>

        {/* Project Summary */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <MaterialCommunityIcons name="clipboard-text" size={20} color="#3B82F6" />
            <Text style={[styles.sectionTitle, { color: themeColors.textPrimary }]}>Project Summary</Text>
          </View>
          <View style={[styles.card, { backgroundColor: themeColors.cardBg }]}>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Project ID</Text>
              <Text style={[styles.value, { color: themeColors.textPrimary }]}>{projectId}</Text>
            </View>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Status</Text>
              <View style={[styles.statusChip, { backgroundColor: themeColors.sectionBg }]}>
                <Text style={[
                  styles.statusChipText,
                  { color: isApproved ? '#10B981' : '#F59E0B' }
                ]}>
                  {isApproved ? 'CUSTOMER APPROVED' : 'QUOTATION GENERATED'}
                </Text>
              </View>
            </View>
            {projectStatus && (
              <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
                <Text style={[styles.label, { color: themeColors.textSecondary }]}>Project Status</Text>
                <View style={[
                  styles.projectStatusChip, 
                  { backgroundColor: getProjectStatusColor(projectStatus) }
                ]}>
                  <Text style={styles.projectStatusChipText}>
                    {getProjectStatusText(projectStatus)}
                  </Text>
                </View>
              </View>
            )}
          </View>
        </View>

        {/* View Site Report Button */}
        <View style={styles.actionSection}>
          <TouchableOpacity
            style={styles.viewReportButton}
            onPress={handleViewReport}
            activeOpacity={0.8}
          >
            <LinearGradient
              colors={['#8B5CF6', '#7C3AED']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={styles.viewReportButtonGradient}
            >
              <MaterialCommunityIcons name="file-document-outline" size={22} color="#FFF" />
              <Text style={styles.viewReportButtonText}>View Site Report</Text>
              <MaterialCommunityIcons name="arrow-right" size={20} color="#FFF" />
            </LinearGradient>
          </TouchableOpacity>
        </View>

        {/* Quotation Breakdown */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <MaterialCommunityIcons name="calculator" size={20} color="#3B82F6" />
            <Text style={[styles.sectionTitle, { color: themeColors.textPrimary }]}>Quotation Breakdown</Text>
          </View>
          <View style={[styles.card, { backgroundColor: themeColors.cardBg }]}>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Material Cost</Text>
              <Text style={styles.amount}>{formatCurrency(materialCost)}</Text>
            </View>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Labour Cost</Text>
              <Text style={styles.amount}>{formatCurrency(labourCost)}</Text>
            </View>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Transport Cost</Text>
              <Text style={styles.amount}>{formatCurrency(transportCost)}</Text>
            </View>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Other Cost</Text>
              <Text style={styles.amount}>{formatCurrency(otherCost)}</Text>
            </View>
            
            <View style={styles.divider} />
            
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Base Total Cost</Text>
              <LinearGradient
                colors={['#3B82F6', '#1E3A8A']}
                style={styles.totalBadge}
              >
                <Text style={styles.totalValue}>{formatCurrency(totalCost)}</Text>
              </LinearGradient>
            </View>
            
            {advanceAmount > 0 && (
              <View style={[
                styles.advanceRow,
                isAdvancePaid && styles.advancePaidRow
              ]}>
                <Text style={[
                  styles.advanceLabel,
                  isAdvancePaid && styles.advancePaidLabel
                ]}>
                  {isAdvancePaid ? 'Advance Paid' : 'Advance Amount Required'}
                </Text>
                <View style={[
                  styles.advanceBadge,
                  isAdvancePaid && styles.advancePaidBadge
                ]}>
                  {isAdvancePaid ? (
                    <>
                      <MaterialCommunityIcons name="check-circle" size={14} color="#10B981" />
                      <Text style={[styles.advanceValue, styles.advancePaidValue]}>
                        {formatCurrency(advanceAmount)}
                      </Text>
                    </>
                  ) : (
                    <>
                      <MaterialCommunityIcons name="arrow-down" size={14} color="#F59E0B" />
                      <Text style={styles.advanceValue}>{formatCurrency(advanceAmount)}</Text>
                    </>
                  )}
                </View>
              </View>
            )}
            
            {isAdvancePaid && advancePayment && (
              <View style={styles.advancePaymentInfo}>
                <Text style={styles.advancePaymentDate}>
                  Paid on {formatDate(advancePayment.paid_at || advancePayment.created_at)}
                </Text>
                {advancePayment.payment_method && (
                  <Text style={styles.advancePaymentMethod}>
                    via {advancePayment.payment_method}
                  </Text>
                )}
              </View>
            )}
          </View>
        </View>

        {/* Extra Charges Section - Show All Extra Charges but Only Pay Buttons for Pending */}
        {extraCharges && extraCharges.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <MaterialCommunityIcons name="alert-circle" size={20} color="#F59E0B" />
              <Text style={[styles.sectionTitle, { color: themeColors.textPrimary }]}>Extra Charges</Text>
            </View>
            <View style={[styles.card, { backgroundColor: themeColors.cardBg }]}>
              {extraCharges.map((charge, index) => {
                const isPending = charge.status === 'pending' && charge.payment_method !== null;
                
                return (
                  <View key={charge.id || index} style={styles.extraChargeItem}>
                    <View style={styles.extraChargeHeader}>
                      <Text style={styles.extraChargeDescription}>
                        {charge.description || 'Extra Charge'}
                      </Text>
                      <View style={[
                        styles.extraChargeStatus,
                        { backgroundColor: charge.status === 'completed' ? '#10B98120' : '#F59E0B20' }
                      ]}>
                        <Text style={[
                          styles.extraChargeStatusText,
                          { color: charge.status === 'completed' ? '#10B981' : '#F59E0B' }
                        ]}>
                          {charge.status === 'completed' ? 'Paid' : 'Pending'}
                        </Text>
                      </View>
                    </View>
                    
                    <View style={styles.extraChargeDetails}>
                      <Text style={[
                        styles.extraChargeAmount,
                        charge.status === 'completed' && styles.extraChargePaidAmount
                      ]}>
                        {formatCurrency(charge.amount)}
                      </Text>
                      
                      {/* Only show Pay Now button for pending charges that have payment method */}
                      {isPending && (
                        <TouchableOpacity
                          style={styles.payExtraButton}
                          onPress={() => handlePayExtraCharge(charge)}
                          activeOpacity={0.7}
                        >
                          <LinearGradient
                            colors={['#F59E0B', '#D97706']}
                            style={styles.payExtraButtonGradient}
                          >
                            <Text style={styles.payExtraButtonText}>Pay Now</Text>
                            <MaterialCommunityIcons name="arrow-right" size={14} color="#FFF" />
                          </LinearGradient>
                        </TouchableOpacity>
                      )}
                      
                      {/* Show paid badge for completed charges */}
                      {charge.status === 'completed' && (
                        <View style={styles.paidBadge}>
                          <MaterialCommunityIcons name="check-circle" size={14} color="#10B981" />
                          <Text style={styles.paidBadgeText}>Paid</Text>
                        </View>
                      )}
                    </View>
                  </View>
                );
              })}
              
              <View style={styles.divider} />
              
              <View style={styles.extraChargeTotal}>
                <Text style={styles.extraChargeTotalLabel}>Total Extra Charges</Text>
                <Text style={styles.extraChargeTotalValue}>
                  {formatCurrency(extraCharges.reduce((sum, c) => sum + parseFloat(c.amount || 0), 0))}
                </Text>
              </View>
            </View>
          </View>
        )}

        {/* Payment Summary Section */}
        {paymentSummary && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <MaterialCommunityIcons name="wallet" size={20} color="#10B981" />
              <Text style={[styles.sectionTitle, { color: themeColors.textPrimary }]}>Payment Summary</Text>
            </View>
            <View style={[styles.paymentCard, { backgroundColor: themeColors.cardBg }]}>
              <View style={styles.paymentRow}>
                <Text style={styles.paymentLabel}>Total Paid</Text>
                <Text style={styles.paymentValueSuccess}>
                  {formatCurrency(paymentSummary.totalPaid)}
                </Text>
              </View>
              
              <View style={styles.paymentRow}>
                <Text style={styles.paymentLabel}>Balance Due</Text>
                <Text style={[
                  styles.paymentValue,
                  paymentSummary.balance > 0 ? styles.paymentValueDanger : styles.paymentValueSuccess
                ]}>
                  {formatCurrency(paymentSummary.balance)}
                </Text>
              </View>
              
              {paymentSummary.hasPendingFinalPayment && (
                <View style={styles.pendingPaymentBadge}>
                  <MaterialCommunityIcons name="clock-outline" size={16} color="#F59E0B" />
                  <Text style={styles.pendingPaymentText}>Final Payment Under Verification</Text>
                </View>
              )}
            </View>
          </View>
        )}

        {/* Quotation Status */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <MaterialCommunityIcons name="information" size={20} color="#3B82F6" />
            <Text style={[styles.sectionTitle, { color: themeColors.textPrimary }]}>Quotation Status</Text>
          </View>
          <View style={[styles.card, { backgroundColor: themeColors.cardBg }]}>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Approved</Text>
              <View style={styles.approvedIndicator}>
                <MaterialCommunityIcons 
                  name={isApproved ? 'check-circle' : 'close-circle'} 
                  size={18} 
                  color={isApproved ? '#10B981' : '#EF4444'} 
                />
                <Text style={[
                  styles.approvedText,
                  { color: isApproved ? '#10B981' : '#EF4444' }
                ]}>
                  {isApproved ? 'Yes' : 'No'}
                </Text>
              </View>
            </View>
            {isApproved && approvedAt ? (
              <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
                <Text style={[styles.label, { color: themeColors.textSecondary }]}>Approved At</Text>
                <Text style={[styles.dateValue, { color: themeColors.textPrimary }]}>{formatDate(approvedAt)}</Text>
              </View>
            ) : null}
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Created At</Text>
              <Text style={[styles.dateValue, { color: themeColors.textPrimary }]}>{formatDate(createdAt)}</Text>
            </View>
            <View style={[styles.row, { borderBottomColor: themeColors.divider }]}>
              <Text style={[styles.label, { color: themeColors.textSecondary }]}>Generated By</Text>
              <Text style={[styles.value, { color: themeColors.textPrimary }]}>{generatedBy || 'N/A'}</Text>
            </View>
          </View>
        </View>

        {/* Action Buttons Section */}
        <View style={styles.actionsContainer}>
          {/* Approve Button */}
          {canApprove && (
            <TouchableOpacity
              style={[styles.actionButton, approving && styles.buttonDisabled]}
              onPress={handleApprove}
              disabled={approving}
              activeOpacity={0.8}
            >
              <LinearGradient
                colors={['#10B981', '#059669']}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                style={styles.actionButtonGradient}
              >
                {approving ? (
                  <ActivityIndicator color="#FFF" />
                ) : (
                  <>
                    <MaterialCommunityIcons name="check-circle" size={22} color="#FFF" />
                    <Text style={styles.actionButtonText}>Approve Quotation</Text>
                  </>
                )}
              </LinearGradient>
            </TouchableOpacity>
          )}

          {/* Pay Advance Button - Only show if advance is not paid */}
          {canPayAdvance && (
            <TouchableOpacity
              style={styles.actionButton}
              onPress={handlePayAdvance}
              activeOpacity={0.8}
            >
              <LinearGradient
                colors={['#F59E0B', '#D97706']}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                style={styles.actionButtonGradient}
              >
                <MaterialCommunityIcons name="bank-transfer" size={22} color="#FFF" />
                <Text style={styles.actionButtonText}>Pay Advance ({formatCurrency(advanceAmount)})</Text>
              </LinearGradient>
            </TouchableOpacity>
          )}

          {/* Download Buttons */}
          <View style={{ flexDirection: 'row' }}>
            <TouchableOpacity
              style={[styles.actionButton, { flex: 1, marginRight: 6 }, downloading && styles.buttonDisabled]}
              onPress={downloadPDF}
              disabled={downloading}
              activeOpacity={0.8}
            >
              <LinearGradient colors={['#3B82F6', '#1E3A8A']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={styles.actionButtonGradient}>
                {downloading ? <ActivityIndicator color="#FFF" /> : (
                  <>
                    <MaterialCommunityIcons name="file-pdf-box" size={20} color="#FFF" />
                    <Text style={[styles.actionButtonText, { fontSize: 13 }]}>PDF</Text>
                  </>
                )}
              </LinearGradient>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.actionButton, { flex: 1, marginRight: 6 }, downloading && styles.buttonDisabled]}
              onPress={downloadCSV}
              disabled={downloading}
              activeOpacity={0.8}
            >
              <LinearGradient colors={['#16A34A', '#15803D']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={styles.actionButtonGradient}>
                {downloading ? <ActivityIndicator color="#FFF" /> : (
                  <>
                    <MaterialCommunityIcons name="file-delimited" size={20} color="#FFF" />
                    <Text style={[styles.actionButtonText, { fontSize: 13 }]}>CSV</Text>
                  </>
                )}
              </LinearGradient>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.actionButton, { flex: 1 }, downloading && styles.buttonDisabled]}
              onPress={downloadExcel}
              disabled={downloading}
              activeOpacity={0.8}
            >
              <LinearGradient colors={['#0369A1', '#075985']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={styles.actionButtonGradient}>
                {downloading ? <ActivityIndicator color="#FFF" /> : (
                  <>
                    <MaterialCommunityIcons name="microsoft-excel" size={20} color="#FFF" />
                    <Text style={[styles.actionButtonText, { fontSize: 13 }]}>Excel</Text>
                  </>
                )}
              </LinearGradient>
            </TouchableOpacity>
          </View>
        </View>

        {/* Approved Badge */}
        {isApproved && (
          <View style={styles.badgeContainer}>
            <LinearGradient
              colors={['#10B981', '#059669']}
              style={styles.approvedBadge}
            >
              <MaterialCommunityIcons name="check-decagram" size={18} color="#FFF" />
              <Text style={styles.badgeText}>APPROVED QUOTATION</Text>
            </LinearGradient>
          </View>
        )}
      </ScrollView>
      
      <BottomNavigation navigation={navigation} activeRoute="ViewQuotation" scrollY={scrollY} />
    </View>
  );
};

const getStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  centerContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  loadingContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  loadingText: {
    fontSize: 16,
    color: '#64748B',
    marginBottom: 20,
    textAlign: 'center',
  },
  loadingIndicator: {
    marginTop: 10,
  },
  errorContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  errorIconContainer: {
    marginBottom: 20,
  },
  errorText: {
    fontSize: 16,
    color: '#EF4444',
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  retryButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 8,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFF',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 80,
  },
  projectHeader: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    padding: 20,
    borderRadius: 24,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  projectHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  projectTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  projectNameText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFF',
    flex: 1,
  },
  statusContainer: {
    marginLeft: 8,
  },
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 4,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFF',
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  locationText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.9)',
  },
  section: {
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    marginBottom: 8,
    gap: 6,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  card: {
    backgroundColor: colors.surface,
    marginHorizontal: 16,
    borderRadius: 20,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  paymentCard: {
    backgroundColor: colors.surface,
    marginHorizontal: 16,
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  label: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
    flex: 1,
  },
  value: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },
  statusChip: {
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusChipText: {
    fontSize: 12,
    fontWeight: '600',
  },
  projectStatusChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  projectStatusChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  amount: {
    fontSize: 15,
    color: colors.textPrimary,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 12,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  totalBadge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFF',
  },
  advanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#FEF3C7',
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: 12,
  },
  advancePaidRow: {
    borderTopColor: '#D1FAE5',
    backgroundColor: '#F0FDF4',
  },
  advanceLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#92400E',
  },
  advancePaidLabel: {
    color: '#065F46',
  },
  advanceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  advancePaidBadge: {
    gap: 6,
  },
  advanceValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#F59E0B',
  },
  advancePaidValue: {
    color: '#10B981',
  },
  advancePaymentInfo: {
    marginTop: 8,
    paddingHorizontal: 4,
  },
  advancePaymentDate: {
    fontSize: 12,
    color: '#64748B',
    fontStyle: 'italic',
  },
  advancePaymentMethod: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  approvedIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  approvedText: {
    fontSize: 14,
    fontWeight: '600',
  },
  dateValue: {
    fontSize: 13,
    color: '#64748B',
  },
  remarksWrapper: {
    marginTop: 12,
  },
  remarksLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 8,
  },
  remarksBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 12,
  },
  remarksText: {
    fontSize: 14,
    color: colors.textPrimary,
    lineHeight: 20,
  },
  imagesWrapper: {
    marginTop: 12,
  },
  imagesLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 8,
  },
  imagesScroll: {
    flexDirection: 'row',
  },
  imageThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginRight: 8,
    overflow: 'hidden',
    backgroundColor: '#F1F5F9',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  actionSection: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  actionsContainer: {
    paddingHorizontal: 16,
    gap: 12,
    marginBottom: 20,
  },
  actionButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  actionButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    gap: 8,
  },
  actionButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
  },
  viewReportButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  viewReportButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    gap: 8,
  },
  viewReportButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    textAlign: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  badgeContainer: {
    paddingHorizontal: 16,
    paddingBottom: 20,
    alignItems: 'center',
  },
  approvedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 30,
    gap: 8,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  badgeText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFF',
  },
  
  // Extra Charge Styles
  extraChargeItem: {
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 12,
  },
  extraChargeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  extraChargeDescription: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
    flex: 1,
  },
  extraChargeStatus: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  extraChargeStatusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  extraChargeDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  extraChargeAmount: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  extraChargePaidAmount: {
    color: '#10B981',
  },
  payExtraButton: {
    overflow: 'hidden',
    borderRadius: 8,
  },
  payExtraButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 4,
  },
  payExtraButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFF',
  },
  paidBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#10B98120',
    borderRadius: 12,
  },
  paidBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#10B981',
  },
  extraChargeTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  extraChargeTotalLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748B',
  },
  extraChargeTotalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  
  // Payment Summary Styles
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  paymentLabel: {
    fontSize: 15,
    color: '#64748B',
    fontWeight: '500',
  },
  paymentValue: {
    fontSize: 16,
    fontWeight: '700',
  },
  paymentValueSuccess: {
    fontSize: 16,
    fontWeight: '700',
    color: '#10B981',
  },
  paymentValueDanger: {
    fontSize: 16,
    fontWeight: '700',
    color: '#EF4444',
  },
  pendingPaymentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    padding: 12,
    borderRadius: 12,
    marginTop: 12,
    gap: 8,
  },
  pendingPaymentText: {
    fontSize: 13,
    color: '#F59E0B',
    fontWeight: '600',
    flex: 1,
  },
});

export default ViewQuotationScreen;
